version: "3"
services:
  postgis:
    image: geographica/postgis:new_version
    ports:
      - "5432:5432"
    volumes:
      - db-data:/data
    environment:
      - POSTGRES_PASSWD=postgres
volumes:
  db-data:
